# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = '''
  {{ hooks?.pre | nl }}
  {% for file in files %}zsh-defer source "{{ file }}"{{ "\n" }}
  {% endfor %}
  {{ hooks?.post | nl }}'''

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.auto-venv]
github = "Skylor-Tang/auto-venv"
apply = ["defer"]

[plugins.direnv]
inline = '''
  if (( $+commands[direnv] )); then
    eval "$(direnv hook zsh)"
  fi'''

[plugins.local]
local = "~/.config/zsh"
use = ["*.zsh"]

[plugins.nvm]
inline = '''
  if [[ -n "${NVM_DIR:-}" ]] && [[ -d "${NVM_DIR}" ]]; then
    if [[ -s "${NVM_DIR}/nvm.sh" ]]; then
      zsh-defer source "${NVM_DIR}/nvm.sh"
    fi

    if [[ -s "${NVM_DIR}/bash_completion" ]]; then
      zsh-defer source "${NVM_DIR}/bash_completion"
    fi

    # Based upon: https://github.com/nvm-sh/nvm#zsh
    autoload -U add-zsh-hook

    load-nvmrc() {
      local nvmrc_path
      nvmrc_path="$(nvm_find_nvmrc)"

      if [ -n "$nvmrc_path" ]; then
        local nvmrc_node_version
        nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

        if [[ "${nvmrc_node_version}" == 'N/A' ]]; then
          nvm install
        elif [[ "${nvmrc_node_version}" != "$(nvm version)" ]]; then
          nvm use
        fi
      elif [[ "$(nvm version)" != "$(nvm version system)" ]]; then
        print 'No `.nvmrc` found in the current path, reverting nvm back to the system version of Node.js'
        nvm use system
      fi
    }

    zsh-defer add-zsh-hook chpwd load-nvmrc
    zsh-defer load-nvmrc
  fi'''

[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["clipboard.zsh", "functions.zsh"]

[plugins.ohmyzsh.hooks]
post = '''
  unfunction uninstall_oh_my_zsh
  unfunction upgrade_oh_my_zsh'''

[plugins.starship]
inline = '''
  if (( $+commands[starship] )); then
    eval "$(starship init zsh)"
  fi'''

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
use = ["autopair.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

# This needs to be loaded as close to the end as possible but before
# zsh-history-substring-search.
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-syntax-highlighting.hooks]
post = """
  # See: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
  if (( ! $+ZSH_HIGHLIGHT_STYLES )); then
    typeset -A ZSH_HIGHLIGHT_STYLES
  fi

  ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta'
  ZSH_HIGHLIGHT_STYLES[globbing]='fg=yellow,bold'"""

# This needs to be loaded after zsh-syntax-highlighting.
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-history-substring-search.hooks]
post = '''
  # Make sure that the terminal is in application mode when zle is active, since
  # only then are values from `$terminfo` valid.
  # From: https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh
  if (( $+terminfo[smkx] )) && (( $+terminfo[rmkx] )); then
    function zle-line-init() { echoti smkx }
    function zle-line-finish() { echoti rmkx }

    zle -N zle-line-init
    zle -N zle-line-finish
  fi

  bindkey "${terminfo[kcuu1]}" history-substring-search-up
  bindkey "${terminfo[kcud1]}" history-substring-search-down'''
